---
apiVersion: batch/v1
kind: Job
metadata:
  name: get-pets-annotations
spec:
  template:
    spec:
      containers:
      - name: get-annotations
        image: inutano/wget
        imagePullPolicy: IfNotPresent
        command: ["wget", "http://www.robots.ox.ac.uk/~vgg/data/pets/data/annotations.tar.gz", "-P", "/pets_data" ]
        volumeMounts:
          - mountPath: "/pets_data"
            name: pets-data
      volumes:
        - name: pets-data
          persistentVolumeClaim:
            claimName: pets-data-claim
      restartPolicy: Never

  backoffLimit: 4