apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
configurations:
- params.yaml

vars:
- fieldref:
    fieldPath: data.pvcName
  name: pvcName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-monitoring
- fieldref:
    fieldPath: data.pvcMountPath
  name: pvcMountPath
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-monitoring
 
patchesJson6902:
- path: deployment_patch.yaml
  target:
    group: apps
    kind: Deployment
    name: tensorboard-tb
    version: v1beta1
