---
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |-
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name: tfserving-mapping-pets-model-get
      prefix: /models/pets-model/
      rewrite: /
      method: GET
      service: pets-model.default:8000
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name: tfserving-mapping-pets-model-post
      prefix: /models/pets-model/
      rewrite: /model/pets-model:predict
      method: POST
      service: pets-model.default:8000
  labels:
    app: pets-model
  name: pets-model
spec:
  ports:
  - name: grpc-tf-serving
    port: 9000
    targetPort: 9000
  - name: http-tf-serving-proxy
    port: 8000
    targetPort: 8000
  selector:
    app: pets-model
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pets-model
  name: pets-model-v1
spec:
  template:
    metadata:
      labels:
        app: pets-model
        version: v1
    spec:
      containers:
      - args:
        - /usr/bin/tensorflow_model_server
        - --port=9000
        - --model_name=pets-model
        - --model_base_path=/pets_data/exported_graphs
        image: gcr.io/kubeflow-images-public/tf-model-server-cpu:v20180327-995786ec
        imagePullPolicy: IfNotPresent
        name: pets-model
        ports:
        - containerPort: 9000
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 1Gi
        securityContext:
          runAsUser: 1000
        volumeMounts:
        - mountPath: /pets_data
          name: nfs
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: pets-data-claim