apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

vars:
- fieldref:
    fieldPath: data.pvcName
  name: pvcName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-serving
- fieldref:
    fieldPath: data.pvcMountPath
  name: pvcMountPath
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-serving

configurations:
- params.yaml

patchesJson6902:
- path: deployment_patch.yaml
  target:
    group: extensions
    kind: Deployment
    name: $(svcName)
    version: v1beta1
