apiVersion: v1
data:
  monitoring_config.txt: |-
    prometheus_config: {
      enable: true,
      path: "/monitoring/prometheus/metrics"
    }
kind: ConfigMap
metadata:
  name: mnist-deploy-local-config
  namespace: kubeflow
