#!/bin/bash
#
# This script creates a PR updating the nmslib index used by search-index-server.
# It uses ks CLI to update the parameters.
# After creating and pushing a commit it uses the hub github CLI to create a PR.
#
# The argument --base can be used to change the owner/org of the repo the PR is opened on.
# To use the main kubeflow/examples repo use 
# --base=kubeflow:master
#
# To use user alex's fork use
# --base=alex/master
set -ex

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null && pwd)"

usage() {
	echo "Usage: update_index.sh --base=OWNER:branch --gitRepo=<github fork repo> --env=<ksonnet environment> --indexFile=<index file> --lookupFile=<lookup file>"
}

# List of required parameters
names=(gitRepo env lookupFile indexFile base)

source "${DIR}/parse_arguments.sh"

if [ ! -z ${help} ]; then
	usage
fi

if [ -z ${dryrun} ]; then
	dryrun=false
fi


git config --global user.email pipeline@localhost
git clone https://${gitToken}@github.com/${gitRepo}.git repo

cd repo
git config credential.helper store
ks param set --env=${env} search-index-server indexFile ${indexFile}
ks param set --env=${env} search-index-server lookupFile ${lookupFile}
git add . && git commit -m "Update the lookup and index file."

FILE=$(mktemp tmp.create_pull_request.XXXX)

cat <<EOF >$FILE
Update the lookup and index file.

This PR is automatically generated by update_index.sh.

This PR updates the index and lookup file used to serve
predictions.
EOF

# Create a pull request
if (! ${dryrun}); then
    git push
    hub pull-request --base=${base} -F ${FILE}
else
	echo "dryrun; not committing to git."
fi
