apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mnist
  namespace: kubeflow
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 20Gi
