apiVersion: 0.2.0
environments:
  default:
    destination:
      namespace: kubeflow
      server: https://35.229.30.77
    k8sVersion: v1.11.5
    path: default
kind: ksonnet.io/app
libraries:
  application:
    name: application
    registry: kubeflow
    version: ""
  argo:
    name: argo
    registry: kubeflow
    version: ""
  common:
    name: common
    registry: kubeflow
    version: ""
  examples:
    name: examples
    registry: kubeflow
    version: ""
  gcp:
    name: gcp
    registry: kubeflow
    version: ""
  jupyter:
    name: jupyter
    registry: kubeflow
    version: ""
  katib:
    name: katib
    registry: kubeflow
    version: ""
  metacontroller:
    name: metacontroller
    registry: kubeflow
    version: ""
  modeldb:
    name: modeldb
    registry: kubeflow
    version: ""
  mpi-job:
    name: mpi-job
    registry: kubeflow
    version: ""
  openvino:
    name: openvino
    registry: kubeflow
    version: ""
  pipeline:
    name: pipeline
    registry: kubeflow
    version: ""
  profiles:
    name: profiles
    registry: kubeflow
    version: ""
  pytorch-job:
    name: pytorch-job
    registry: kubeflow
    version: ""
  seldon:
    name: seldon
    registry: kubeflow
    version: ""
  tf-serving:
    name: tf-serving
    registry: kubeflow
    version: ""
  tf-training:
    name: tf-training
    registry: kubeflow
    version: ""
name: ks_app
registries:
  kubeflow:
    protocol: fs
    uri: /home/jlewi/git_kubeflow/kubeflow
version: 0.0.1
