apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |-
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name: web-ui_mapping
      prefix: /kubeflow/mnist/
      rewrite: /
      service: web-ui.kubeflow
  name: web-ui
  namespace: kubeflow
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: web-ui
  type: ClusterIP
