apiVersion: 0.1.0
kind: ksonnet.io/app
libraries:
  tf-job:
    gitVersion:
      commitSha: 867e74ebcc2002f1f64250e24813db7047fb526f
      refSpec: master
    name: tf-job
    registry: kubeflow
name: kubeflow
registries:
  incubator:
    gitVersion:
      commitSha: 40285d8a14f1ac5787e405e1023cf0c07f6aa28c
      refSpec: master
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    gitVersion:
      commitSha: 867e74ebcc2002f1f64250e24813db7047fb526f
      refSpec: master
    protocol: github
    uri: github.com/kubeflow/kubeflow/tree/master/kubeflow
version: 0.0.1
