apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xgboost-synthetic
  namespace: kubeflow
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
