apiVersion: 0.1.0
environments:
  cloud:
    destination:
      namespace: namespace
      server: https://35.188.73.10
    k8sVersion: v1.7.0
    path: cloud
  default:
    destination:
      namespace: default
      server: https://35.188.73.10
    k8sVersion: v1.7.0
    path: default
  jlewi:
    destination:
      namespace: kubeflow
      server: https://35.196.4.129
    k8sVersion: v1.9.6
    path: jlewi
  kubecon-gh-demo-1:
    destination:
      namespace: kubeflow
      server: https://35.231.60.188
    k8sVersion: v1.7.0
    path: kubecon-gh-demo-1
kind: ksonnet.io/app
libraries:
  core:
    gitVersion:
      commitSha: 3da7eb254cefd6a8a79ed7db57a30adfb91b734e
      refSpec: master
    name: core
    registry: kubeflow
  examples:
    gitVersion:
      commitSha: 3da7eb254cefd6a8a79ed7db57a30adfb91b734e
      refSpec: master
    name: examples
    registry: kubeflow
  seldon:
    gitVersion:
      commitSha: 3da7eb254cefd6a8a79ed7db57a30adfb91b734e
      refSpec: master
    name: seldon
    registry: kubeflow
name: ks-kubeflow
registries:
  kubeflow:
    gitVersion:
      commitSha: 3be196cfa1d68d9a33e0674c133ffbbcc3e57d46
      refSpec: v0.2.0-rc.1
    protocol: github
    uri: github.com/kubeflow/kubeflow/tree/v0.2.0-rc.1/kubeflow
version: 0.0.1
