apiVersion: 0.1.0
environments:
  default:
    destination:
      namespace: gcp-deploy
      server: https://35.188.73.10
    k8sVersion: v1.9.6
    path: default
kind: ksonnet.io/app
name: ks-app
version: 0.0.1
