#This container contains your model and any helper scripts specific to your model.
FROM mytfserver:1.0

ADD model.py /opt/model.py
ADD export.py /opt/export.py

RUN chmod +x /opt/model.py
RUN chmod +x /opt/export.py

CMD ["python", "/opt/model.py"]
