{
  global: {
    // User-defined global parameters; accessible to all component and environments, Ex:
    // replicas: 4,
  },
  components: {
    // Component-level parameters, defined initially from 'ks prototype use ...'
    // Each object below should correspond to a component in the components/ directory
    code_search: {
      bucket: "kubeflow-ci_temp",
      name: "kubeflow-code_search",
      namespace: "kubeflow-test-infra",
      prow_env: "BUILD_NUMBER=997a,BUILD_ID=997a,JOB_NAME=kubeflow-examples-presubmit-test,JOB_TYPE=presubmit,PULL_NUMBER=374,REPO_NAME=examples,REPO_OWNER=kubeflow",
    },
    gis: {
      bucket: "kubeflow-ci_temp",
      name: "kubeflow-gis",
      namespace: "kubeflow-test-infra",
      prow_env: "BUILD_NUMBER=997a,BUILD_ID=997a,JOB_NAME=kubeflow-examples-presubmit-test,JOB_TYPE=presubmit,PULL_NUMBER=374,REPO_NAME=examples,REPO_OWNER=kubeflow",
    },
    mnist: {
      bucket: "kubeflow-ci_temp",
      name: "kubeflow-mnist",
      namespace: "kubeflow-test-infra",
      prow_env: "BUILD_NUMBER=997a,BUILD_ID=997a,JOB_NAME=kubeflow-examples-presubmit-test,JOB_TYPE=presubmit,PULL_NUMBER=374,REPO_NAME=examples,REPO_OWNER=kubeflow",
    },
    xgboost_ames_housing: {
      bucket: "kubeflow-ci_temp",
      name: "kubeflow-xgboost-ames-housing",
      namespace: "kubeflow-test-infra",
      prow_env: "BUILD_NUMBER=997a,BUILD_ID=997a,JOB_NAME=kubeflow-examples-presubmit-test,JOB_TYPE=presubmit,PULL_NUMBER=374,REPO_NAME=examples,REPO_OWNER=kubeflow",
    },
    workflows: {
      bucket: "kubeflow-ci_temp",
      name: "kubeflow-examples-presubmit-test-374-6e32",
      namespace: "kubeflow-test-infra",
      prow_env: "BUILD_NUMBER=997a,BUILD_ID=997a,JOB_NAME=kubeflow-examples-presubmit-test,JOB_TYPE=presubmit,PULL_NUMBER=374,REPO_NAME=examples,REPO_OWNER=kubeflow",
    },
    "pytorch-mnist-webui-release": {
      bucket: "kubeflow-ci_temp",
      cluster: "kubeflow-testing",
      dockerfile: "Dockerfile",
      dockerfileDir: "kubeflow/examples/pytorch_mnist/web-ui",
      extra_args: "null",
      extra_repos: "kubeflow/testing@HEAD",
      gcpCredentialsSecretName: "gcp-credentials",
      image: "pytorch-mnist-webui",
      name: "pytorch-mnist-webui-release",
      namespace: "kubeflow-ci",
      nfsVolumeClaim: "nfs-external",
      project: "kubeflow-ci",
      prow_env: "REPO_OWNER=kubeflow,REPO_NAME=kubeflow,PULL_BASE_SHA=master",
      testing_image: "gcr.io/kubeflow-ci/test-worker",
      versionTag: "latest",
      zone: "us-central1-a",
    },
    "pytorch-mnist-serve-release": {
      bucket: "kubeflow-ci_temp",
      cluster: "kubeflow-testing",
      dockerfile: "Dockerfile",
      dockerfileDir: "kubeflow/examples/pytorch_mnist/serving/seldon-wrapper",
      extra_args: "null",
      extra_repos: "kubeflow/testing@HEAD",
      gcpCredentialsSecretName: "gcp-credentials",
      image: "mnistddpserving",
      name: "pytorch-mnist-serve-release",
      namespace: "kubeflow-ci",
      nfsVolumeClaim: "nfs-external",
      project: "kubeflow-ci",
      prow_env: "REPO_OWNER=kubeflow,REPO_NAME=kubeflow,PULL_BASE_SHA=master",
      testing_image: "gcr.io/kubeflow-ci/test-worker",
      versionTag: "latest",
      zone: "us-central1-a",
    },
    "pytorch-mnist-cpu-release": {
      bucket: "kubeflow-ci_temp",
      cluster: "kubeflow-testing",
      dockerfile: "Dockerfile.traincpu",
      dockerfileDir: "kubeflow/examples/pytorch_mnist/training/ddp/mnist",
      extra_args: "null",
      extra_repos: "kubeflow/testing@HEAD",
      gcpCredentialsSecretName: "gcp-credentials",
      image: "pytorch-mnist-ddp-cpu",
      name: "pytorch-mnist-cpu-release",
      namespace: "kubeflow-ci",
      nfsVolumeClaim: "nfs-external",
      project: "kubeflow-ci",
      prow_env: "REPO_OWNER=kubeflow,REPO_NAME=kubeflow,PULL_BASE_SHA=master",
      testing_image: "gcr.io/kubeflow-ci/test-worker",
      versionTag: "latest",
      zone: "us-central1-a",
    },
    "pytorch-mnist-gpu-release": {
      bucket: "kubeflow-ci_temp",
      cluster: "kubeflow-testing",
      dockerfile: "Dockerfile.traingpu",
      dockerfileDir: "kubeflow/examples/pytorch_mnist/training/ddp/mnist",
      extra_args: "null",
      extra_repos: "kubeflow/testing@HEAD",
      gcpCredentialsSecretName: "gcp-credentials",
      image: "pytorch-mnist-ddp-gpu",
      name: "pytorch-mnist-gpu-release",
      namespace: "kubeflow-ci",
      nfsVolumeClaim: "nfs-external",
      project: "kubeflow-ci",
      prow_env: "REPO_OWNER=kubeflow,REPO_NAME=kubeflow,PULL_BASE_SHA=master",
      testing_image: "gcr.io/kubeflow-ci/test-worker",
      versionTag: "latest",
      zone: "us-central1-a",
    },
  },
}
