apiVersion: kubeflow.org/v1beta1
kind: TFJob
metadata:
  name: $(trainingName)
  namespace: kubeflow
spec:
  tfReplicaSpecs:
    Worker:
      replicas: %numWorkers%
      template:
        spec:
          containers:
          - args:
            - --tf-model-dir=$(modelDir)
            - --tf-export-dir=$(exportDir)
            - --tf-train-steps=200
            - --tf-batch-size=100
            - --tf-learning-rate=0.01
            command:
            - /usr/bin/python
            - /opt/model.py
            env:
            - name: modelDir
              value: $(modelDir)
            - name: exportDir
              value: $(exportDir)        
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: $(GOOGLE_APPLICATION_CREDENTIALS)
            image: training-image
            name: tensorflow
            volumeMounts:
            - mountPath: $(secretMountPath)
              name: user-gcp-sa
              readOnly: true
            workingDir: /opt
          restartPolicy: OnFailure
          volumes:
          - name: user-gcp-sa
            secret:
              secretName: $(secretName)
