apiVersion: v1
kind: Service
metadata:
  name: pipeline-worker-2
  namespace: kubeflow-user-example-com 
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30390
    protocol: TCP
    targetPort: 3000
  selector: 
    pod-name: worker-2

