- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    mountPath: /secret/gcp-credentials
    name: user-gcp-sa
    readOnly: true
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: user-gcp-sa
    secret:
      secretName: user-gcp-sa
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: GOOGLE_APPLICATION_CREDENTIALS
    value: /secret/gcp-credentials/user-gcp-sa.json
