apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patchesJson6902:
- path: deployment_patch.yaml
  target:
    group: extensions
    kind: Deployment
    name: $(svcName)
    version: v1beta1
