apiVersion: 0.3.0
environments:
  jlewi:
    destination:
      namespace: jlewi
      server: https://35.196.210.94
    k8sVersion: v1.11.5
    path: jlewi
  test-env-d5e3:
    destination:
      namespace: jlewi
      server: https://35.196.210.94
    k8sVersion: v1.11.5
    path: test-env-d5e3
kind: ksonnet.io/app
libraries:
  kubeflow/tf-serving:
    name: tf-serving
    registry: kubeflow
    version: fed535eaa276220e4edf59530c0629f4375a40a9
name: ks_app
registries:
  incubator:
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    protocol: github
    uri: github.com/kubeflow/kubeflow/tree/v0.4-branch/kubeflow
version: 0.0.1
