apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

configurations:
- params.yaml

vars:
- fieldref:
    fieldPath: data.S3_ENDPOINT
  name: S3_ENDPOINT
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-monitoring
- fieldref:
    fieldPath: data.AWS_ENDPOINT_URL
  name: AWS_ENDPOINT_URL
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-monitoring
- fieldref:
    fieldPath: data.AWS_REGION
  name: AWS_REGION
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-monitoring
- fieldref:
    fieldPath: data.BUCKET_NAME
  name: BUCKET_NAME
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-monitoring
- fieldref:
    fieldPath: data.S3_USE_HTTPS
  name: S3_USE_HTTPS
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-monitoring
- fieldref:
    fieldPath: data.S3_VERIFY_SSL
  name: S3_VERIFY_SSL
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-monitoring
- fieldref:
    fieldPath: metadata.name
  name: awsSecretName
  objref:
    apiVersion: v1
    kind: Secret
    name: aws-creds
- fieldref:
    fieldPath: data.awsAccessKeyIDName
  name: awsAccessKeyIDName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-monitoring
- fieldref:
    fieldPath: data.awsSecretAccessKeyName
  name: awsSecretAccessKeyName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-monitoring

patchesJson6902:
- path: deployment_patch.yaml
  target:
    group: apps
    kind: Deployment
    name: tensorboard-tb
    version: v1beta1
