apiVersion: kubeflow.org/v1alpha1
kind: TFJob
metadata:
  name: tf-job-issue-summarization
  namespace: ${NAMESPACE}
spec:
  replicaSpecs:
  - replicas: 1
    template:
      spec:
        containers:
        - image: gcr.io/agwl-kubeflow/tf-job-issue-summarization:latest
          name: tensorflow
          volumeMounts:
          - name: gcp-credentials
            mountPath: "/secret/gcp-credentials"
            readOnly: true
          command: ['python']
          args:
          - '/workdir/train.py'
          - '--sample_size=1000'
          - '--input_data_gcs_bucket=kubeflow-examples'
          - '--input_data_gcs_path=github-issue-summarization-data/github-issues.zip'
          - '--output_model_gcs_bucket=kubeflow-examples'
          - '--output_model_gcs_path=github-issue-summarization-data/output_model.h5'
          env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/secret/gcp-credentials/key.json"
        volumes:
        - name: gcp-credentials
          secret:
            secretName: gcp-credentials
        restartPolicy: OnFailure
    tfReplicaType: MASTER
  terminationPolicy:
    chief:
      replicaIndex: 0
      replicaName: MASTER
