apiVersion: 0.1.0
environments:
  default:
    destination:
      namespace: default
      server: https://35.188.86.227
    k8sVersion: v1.7.0
    path: default
kind: ksonnet.io/app
libraries:
  core:
    gitVersion:
      commitSha: 20bdb46ee436b56fb9e3690d2a383b2afc8989f4
      refSpec: v0.1.0
    name: core
    registry: kubeflow
  tf-job:
    gitVersion:
      commitSha: 20bdb46ee436b56fb9e3690d2a383b2afc8989f4
      refSpec: v0.1.0
    name: tf-job
    registry: kubeflow
  tf-serving:
    gitVersion:
      commitSha: 20bdb46ee436b56fb9e3690d2a383b2afc8989f4
      refSpec: v0.1.0
    name: tf-serving
    registry: kubeflow
name: demo
registries:
  incubator:
    gitVersion:
      commitSha: 40285d8a14f1ac5787e405e1023cf0c07f6aa28c
      refSpec: master
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    gitVersion:
      commitSha: 20bdb46ee436b56fb9e3690d2a383b2afc8989f4
      refSpec: v0.1.0
    protocol: github
    uri: github.com/kubeflow/kubeflow/tree/v0.1.0/kubeflow
version: 0.0.1
