apiVersion: 0.2.0
environments:
  default:
    destination:
      namespace: default
      server: https://35.188.86.227
    k8sVersion: v1.7.0
    path: default
kind: ksonnet.io/app
libraries:
  core:
    name: core
    registry: kubeflow
    version: 3be196cfa1d68d9a33e0674c133ffbbcc3e57d46
  tf-job:
    name: tf-job
    registry: kubeflow
    version: 3be196cfa1d68d9a33e0674c133ffbbcc3e57d46
  tf-serving:
    name: tf-serving
    registry: kubeflow
    version: 3be196cfa1d68d9a33e0674c133ffbbcc3e57d46
name: demo
registries:
  incubator:
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    protocol: github
    uri: github.com/kubeflow/kubeflow/tree/v0.2.0-rc.1/kubeflow
version: 0.0.1
