apiVersion: 0.2.0
environments:
  default:
    destination:
      namespace: default
      server: https://35.188.86.227
    k8sVersion: v1.7.0
    path: default
kind: ksonnet.io/app
libraries:
  core:
    name: core
    registry: kubeflow
    version: 20bdb46ee436b56fb9e3690d2a383b2afc8989f4
  tf-job:
    name: tf-job
    registry: kubeflow
    version: 20bdb46ee436b56fb9e3690d2a383b2afc8989f4
  tf-serving:
    name: tf-serving
    registry: kubeflow
    version: 20bdb46ee436b56fb9e3690d2a383b2afc8989f4
name: demo
registries:
  incubator:
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    protocol: github
    uri: github.com/kubeflow/kubeflow/tree/v0.1.0/kubeflow
version: 0.0.1
