apiVersion: 0.2.0
environments:
  default:
    destination:
      namespace: default
      server: https://35.188.86.227
    k8sVersion: v1.7.0
    path: default
  gke:
    destination:
      namespace: kubeflow
      server: https://35.227.190.159
    k8sVersion: v1.10.6
    path: gke
kind: ksonnet.io/app
libraries:
  core:
    name: core
    registry: kubeflow
    version: 457cf677ba14ceb2a9519e87580ad9aaad697d4c
  tf-serving:
    name: tf-serving
    registry: kubeflow
    version: 457cf677ba14ceb2a9519e87580ad9aaad697d4c
name: demo
registries:
  incubator:
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    protocol: github
    uri: github.com/kubeflow/kubeflow/tree/v0.2.4/kubeflow
version: 0.0.1
