apiVersion: 0.0.1
kind: ksonnet.io/app
libraries:
  core:
    gitVersion:
      commitSha: c46406be24e6daf9dddd17c5a02b2a44f83710ef
      refSpec: master
    name: core
    registry: kubeflow
  tf-job:
    gitVersion:
      commitSha: c46406be24e6daf9dddd17c5a02b2a44f83710ef
      refSpec: master
    name: tf-job
    registry: kubeflow
  tf-serving:
    gitVersion:
      commitSha: c46406be24e6daf9dddd17c5a02b2a44f83710ef
      refSpec: master
    name: tf-serving
    registry: kubeflow
name: rl-app
registries:
  incubator:
    gitVersion:
      commitSha: ea3408d44c2d8ea4d321364e5533d5c60e74bce0
      refSpec: master
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    gitVersion:
      commitSha: c46406be24e6daf9dddd17c5a02b2a44f83710ef
      refSpec: master
    protocol: github
    uri: github.com/google/kubeflow/tree/master/kubeflow
version: 0.0.1
