#This container contains your model and any helper scripts specific to your model.
FROM tensorflow/tensorflow:1.11.0

COPY model.py /opt/model.py

ENTRYPOINT ["/usr/bin/python"]
CMD ["/opt/model.py"]
