#
# Copyright 2017 The Kubeflow Examples Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM tensorflow/tensorflow:{tensorflow_image_tag}

RUN apt-get update

RUN pip install gym==0.9.4
RUN pip install pybullet==1.7.5
RUN pip install ruamel.yaml==0.15.35

# Needed for rendering and uploading renders
RUN apt-get install -y libav-tools ffmpeg
RUN pip install google-cloud-storage==1.7.0

ADD third_party/agents /app/agents/
RUN cd /app/agents && pip install -e .

WORKDIR /app
