From python:3.7

RUN pip3 install numpy
RUN pip3 install pandas
RUN pip3 install nltk
RUN pip3 install torch
RUN pip3 install joblib
RUN pip3 install sklearn
RUN pip3 install flask
RUN pip3 install requests

WORKDIR /http-port
ADD . /http-port
