apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tensorboard-tb
  namespace: kubeflow
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tensorboard
        tb-job: tensorboard
      name: tensorboard
      namespace: kubeflow
    spec:
      containers:
      - command:
        - /usr/local/bin/tensorboard
        - --logdir=$(logDir)
        - --port=80
        env:
        - name: logDir
          value: $(logDir)
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: $(GOOGLE_APPLICATION_CREDENTIALS)
        image: tensorflow/tensorflow:1.11.0
        name: tensorboard
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: $(secretMountPath)
          name: user-gcp-sa
          readOnly: true
      volumes:
      - name: user-gcp-sa
        secret:
          secretName: $(secretName)
