apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |-
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name: tensorboard_mapping
      prefix: /kubeflow/tensorboard/mnist
      rewrite: /
      service: tensorboard-tb.kubeflow
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name: tensorboard_mapping_data
      prefix: /kubeflow/tensorboard/mnist/data/
      rewrite: /data/
      service: tensorboard-tb.kubeflow
  name: tensorboard-tb
  namespace: kubeflow
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: tensorboard
    tb-job: tensorboard
