apiVersion: 0.1.0
kind: ksonnet.io/app
libraries:
  tf-job:
    gitVersion:
      commitSha: 8b48d28127cb719410a9c40be214d3c76c2b4cb7
      refSpec: master
    name: tf-job
    registry: kubeflow
name: app
registries:
  incubator:
    gitVersion:
      commitSha: 422d521c05aa905df949868143b26445f5e4eda5
      refSpec: master
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    gitVersion:
      commitSha: 8b48d28127cb719410a9c40be214d3c76c2b4cb7
      refSpec: master
    protocol: github
    uri: github.com/kubeflow/kubeflow/tree/master/kubeflow
version: 0.0.1
