---
apiVersion: batch/v1
kind: Job
metadata:
  name: get-pets-dataset
spec:
  template:
    spec:
      containers:
      - name: get-data
        image: inutano/wget
        imagePullPolicy: IfNotPresent
        command: ["wget",  "http://www.robots.ox.ac.uk/~vgg/data/pets/data/images.tar.gz", "-P", "/pets_data"]
        volumeMounts:
          - mountPath: "/pets_data"
            name: pets-data
      volumes:
        - name: pets-data
          persistentVolumeClaim:
            claimName: pets-data-claim
      restartPolicy: Never

  backoffLimit: 4