---
apiVersion: batch/v1
kind: Job
metadata:
  name: decompress-images
spec:
  template:
    spec:
      containers:
      - name: decompress-images
        image: ubuntu:16.04
        imagePullPolicy: IfNotPresent
        command: ["tar", "--no-same-owner", "-xzvf", "/pets_data/images.tar.gz", "-C", "/pets_data"]
        volumeMounts:
          - mountPath: "/pets_data"
            name: pets-data
      volumes:
        - name: pets-data
          persistentVolumeClaim:
            claimName: pets-data-claim
      restartPolicy: Never

  backoffLimit: 4
