---
apiVersion: batch/v1
kind: Job
metadata:
  name: decompress-annotations
spec:
  template:
    spec:
      containers:
      - name: decompress-annotations
        image: ubuntu:16.04
        imagePullPolicy: IfNotPresent
        command: ["tar", "-xzvf", "/pets_data/annotations.tar.gz", "-C", "/pets_data"]
        volumeMounts:
          - mountPath: "/pets_data"
            name: pets-data
      volumes:
        - name: pets-data
          persistentVolumeClaim:
            claimName: pets-data-claim
      restartPolicy: Never

  backoffLimit: 4