---
apiVersion: batch/v1
kind: Job
metadata:
  name: get-fasterrcnn-config
spec:
  template:
    spec:
      containers:
      - name: get-model
        image: inutano/wget
        imagePullPolicy: IfNotPresent
        command: ["wget", "--no-check-certificate", "https://raw.githubusercontent.com/ldcastell/examples/distributedTrainingExample/object_detection/conf/faster_rcnn_resnet101_pets.config", "-P",  "/pets_data"]
        volumeMounts:
          - mountPath: "/pets_data"
            name: pets-data
      volumes:
        - name: pets-data
          persistentVolumeClaim:
            claimName: pets-data-claim
      restartPolicy: Never
  backoffLimit: 4
