---
apiVersion: kubeflow.org/v1alpha2
kind: TFJob
metadata:
  name: pets-training
spec:
  tfReplicaSpecs:
    PS:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
          - name: tensorflow
            image: lcastell/pets_object_detection
            resources:
              limits:
                nvidia.com/gpu: 1
            imagePullPolicy: IfNotPresent
            workingDir: /models
            command:
              - "python"
              - "research/object_detection/train.py"
            args:
              - "--logtostderr"
              - "--pipeline_config_path=/pets_data/faster_rcnn_resnet101_pets.config"
              - "--train_dir=/pets_data/train"
            volumeMounts:
              - mountPath: "/pets_data"
                name: pets-data
          volumes:
            - name: pets-data
              persistentVolumeClaim:
                claimName: pets-data-claim
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
          - name: tensorflow
            image: lcastell/pets_object_detection
            resources:
              limits:
                nvidia.com/gpu: 1
            imagePullPolicy: IfNotPresent
            workingDir: /models
            command:
              - "python"
              - "research/object_detection/train.py"
            args:
              - "--logtostderr"
              - "--pipeline_config_path=/pets_data/faster_rcnn_resnet101_pets.config"
              - "--train_dir=/pets_data/train"
            volumeMounts:
              - mountPath: "/pets_data"
                name: pets-data
          volumes:
            - name: pets-data
              persistentVolumeClaim:
                claimName: pets-data-claim
