kind: PersistentVolume
apiVersion: v1
metadata:
  name: vol
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/stateful_partition/data2/"
