apiVersion: kubeflow.org/v1beta1
kind: TFJob
metadata:
  name: $(trainingName)
  namespace: kubeflow
spec:
  tfReplicaSpecs:
    Chief:
      replicas: 1
      template:
        spec:
          containers:
          - args:
            - --tf-model-dir=/mnt
            - --tf-export-dir=/mnt/export
            - --tf-train-steps=200
            - --tf-batch-size=100
            - --tf-learning-rate=0.01
            command:
            - /usr/bin/python
            - /opt/model.py
            image: training-image
            name: tensorflow
            volumeMounts:
            - mountPath: /mnt
              name: local-storage
            workingDir: /opt
          restartPolicy: OnFailure
          volumes:
          - name: local-storage
            persistentVolumeClaim:
              claimName: $(pvcName)